language: python
cache: pip
python:
  - "3.6"
dist: trusty
services:
  - postgresql
env:
  global:
  - SOURCE_FOLDER=gnosis
  - PIP_USE_MIRRORS=true
addons:
  postgresql: "9.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - npm install -g ganache-cli@6.1.4
script:
  - ganache-cli -d -p 8545 --defaultBalanceEther 10000 --gasLimit 10000000 -a 30 > /dev/null &
  - sleep 5
  - coverage run --source=$SOURCE_FOLDER manage.py test --settings=config.settings.test
after_success:
  - coveralls
deploy:
  provider: script
  script: bash scripts/deploy.sh "${PYPI_USER}" "${PYPI_PASS}"
  skip_cleanup: true
  on:
    tags: true
